### ISSUE TITLE
Reunião 27/10/2020

### ISSUE THREAD

**Issue by RafaellaJunqueira** [BOSS-BigOpenSourceSister/BigSister#117]
# Reunião semanal 

- **Data:** 27 de outubro de 2020
- **Ata da reunião anterior**: [Reunião dia 20.10](../issues/99  )
- **Participantes**:
  - Rafaella
  - Bruna Pinos
  - Bruna Nayara
  - Débora
  - Marina
  - Clarissa

### Acompanhamento das ações pendentes da última reunião
- [x] Falar com entrevistada/entrevistadoras e definir data da Talk Like a Boss ([issue da talk](../issues/102))
- [ ] Abrir issue de exemplo/definição de entidades (@naiieandrade @RafaellaJunqueira) 

### Itens a serem debatidos
- [ ] Atribuir responsáveis para cada item do [checklist de encerramento](../issues/108). **Ficou para semana que vem**
- [x] Faremos mesmo as camisetas e stickers? Se sim, atribuir responsáveis por essa [issue em questão](../issues/113)
- [x] O que entregar para o Challenge

### Tarefas criadas
- [ ] Definir a data do evento de fechamento com mentoradas(09/11 a 15/11); @dehatanes
- [ ] Criar issue de checklist gigantão do challenge (@RafaellaJunqueira )
- [ ] Criar issue de última mentoria (perguntas e tópicos a serem abordados)
- [ ] **Finalizar o documento do Challenge !!!**

### itens a pensar para reunião de planejamento do próximo ciclo
- Entender o que foi bom e ruim no checkpoint com mentoradas (@Joranhezon )
- Fechar o [PR da Carol](../issues/112) sobre adição das experiências do Checkpoint geral ao Post Mortem;
- Issues que poderiam ser finalizadas: [Onboarding](../issues/75), [Roadmap boilerplate](../issues/20), [Tutorial StreamYard](../issues/53), [Tempinho na descrição dos vídeos](../issues/92);
- Issues que poderiam ser fechadas: todas com a label "O que fazer?", [issue de engajamento](../issues/81), [Newsletter](../issues/82), [formulários](../issues/96) (só pq isso é mais pra próxima edição mesmo), [Roadmap do projeto](../issues/101), [conteúdo de ontem](#114);
- Issues que precisam de um destino: [gipage](../issues/22), [conteúdo em áudio](../issues/67), [assignBot](../issues/79);
- Issues que eu não entendi nada e gostaria de saber se vão pra frente ou não kkk: [Documentar em inglês](../issues/33);

@BOSS-BigOpenSourceSister/mentoras

**Comment by clarissalimab** [comment]
Acho que como essa semana é a última, a gente pode usar o tempo pra pensar no encerramento e pra trabalhar no que a gente vai entregar pro Challenge. Os pontos da retrô a gente pode trazer pra semana que vem ou pra quando a gente for sentar pra levantar os pontos do próximo ciclo. O que vocês acham?
