### ISSUE TITLE
Reunião 02/02/2021

### ISSUE THREAD

**Issue by jufajardini** [BOSS-BigOpenSourceSister/BigSister#135]
# Reunião semanal 

- **Data:** 02 fevereiro de 2021
- **Ata da reunião anterior**: [Link](https://github.com/BOSS-BigOpenSourceSister/BigSister/issues/128)

### Participantes:
  - 
 
### Acompanhamento das ações pendentes da última reunião

- [ ] Material sobre Diversidade e Inclusão https://github.com/BOSS-BigOpenSourceSister/BigSister/issues/125
- [ ] Formulário De Inscrição de Mentoras e Organizadoras https://github.com/BOSS-BigOpenSourceSister/BigSister/issues/134
- [ ] Publicações no twitter https://github.com/BOSS-BigOpenSourceSister/BigSister/issues/132 
- [x] Criar Formulário de Acompanhamento de Mentora/Mentorada https://github.com/BOSS-BigOpenSourceSister/BigSister/issues/96

### Itens a serem debatidos
**OBS: Entramos oficialmente no nosso [calendário](https://github.com/BOSS-BigOpenSourceSister/BigSister/blob/submission-phase2/BOSS%20milestones.pdf).**

- [x]  Tópico 1: E-mail da Iana sobre parceria com Programaria **Importantíssimo**
- [x]  Tópico 2: Formulário de inscricão de mentoras e outros cargos que precisamos. (Precisa estar pronto semana que vem) **Importantíssimo**
- [x]  Tópico 3: Preparar material para mentoras.(Precisa ser feito e revisado até o mês que vem)

### Tarefas criadas

- [x] Levantar as tarefas importantes da semana (@jufajardini)
- [x] Formulário de inscrição para as mentoradas (@ludimila)
- [ ] Tweets de divulgação da temporada (@clarissalimab @Joranhezon)
- [x] Responder ao email da Iana e enviar a logo da BOSS (@Joranhezon) 

@BOSS-BigOpenSourceSister/mentoras

**Comment by Joranhezon** [comment]
Galera, sobre o e-mail da Iana, peco que me avisem no grupo qual foi o veredito para que eu a responda. :)

**Comment by jufajardini** [comment]
Próxima reunião: temos que fechar / decidir uma ferramenta/ canal/ formato de comunicação interna que ajude a deixar as informações importantes visíveis para que sejam tratadas em tempo hábil.

**Comment by jufajardini** [comment]
Possibilidades: stand-up meetings? Threads em algo como um chat especial no telegram?

**Comment by contraexemplo** [comment]
Telegram channels: https://telegram.org/tour/channels

**Comment by contraexemplo** [comment]
## Descobertas sobre mentoria

Durante dois meses entrevistei mentores de comunidades abertas. O que compartilho com vocês são conclusões tiradas através das respostas que recebi e que acredito que serão úteis para BOSS.

### Ideias gerais
- Mentores se voluntariam em projetos como Outreachy e Google Summer of Code principalmente por dois motivos: (1) encorajamento comunitário ou organizacional (uma vez que a mentoria é vista como próximo passo lógico na carreira de alguém que começa a acumular bastante experiência) (2) uma imensa vontade de ajudar (muitas vezes desencadeada por acontecimentos que caracterizo como "catárticos", eventos que fazem com que a pessoa perceba o privilégio que ela tem e que a ela pode usá-lo para ajudar outras pessoas).
- A co-mentoria é uma prática bastante celebrada entre comunidades. De forma geral, considera-se mentorar alguém sozinho uma ideia não muito boa, especialmente se é a primeira vez que aquela pessoa mentora alguém. Uma mentoria solo coloca a carga de trabalho somente em uma pessoa. A co-mentoria permite que duas ou mais pessoas dividam essa carga sem que haja algum tipo de prejuízo para o mentorando. Além disso, a co-mentoria traz uma maior multidisciplinaridade ao alcance do mentorando: pessoas de áreas diferentes podem ajudá-la a expandir os seus conhecimentos e a conviver com pessoas de estilos de trabalho diferentes.

### Desafios
Trabalhamos com pessoas de diferentes culturas, línguas nativas e que muito provavelmente pertencem a grupos mais vulneráveis.Algumas pessoas são ensinadas a não questionar figuras de autoridade, e por isso podem não falar conosco sobre os seus problemas. E, por mais que confiemos em nossos mentores, um relacionamento mentor/mentorando ainda traz um desequilíbrio que pode abrir espaço para abusos. Por isso, é necessário se tornar mais familiar com conceitos relacionados a [safeguarding](https://www.scie.org.uk/safeguarding/adults/introduction/highlights).

## Conduzindo entrevistas e fazendo perguntas
Fazer perguntas é difícil. Fazer perguntas que não influenciem a resposta das pessoas sendo entrevistadas é ainda mais difícil. Três pontos-chave para fazer boas perguntas:
1. Não conduza uma pergunta tentando reescrever o que alguém relatou (algo como "você considerou difícil encontrar o botão verde?" quando alguém disse que passou algum tempo navegando pela interface).
2. Evite jargões. Escreva as perguntas da forma mais simples possível.
3.  Permita que a própria pessoa descreva as suas experiências. Não assuma que você sabe o que ela sente ou vivencia.

Adicionalmente, conversas face-a-face são uma ótima maneira de se conectar com as pessoas que você está entrevistando. Apesar de tornarem anotações um pouco mais difícil, é excelente para que você as conheça. Por outro lado, entrevistas por texto (especialmente as por e-mail) permitem que o entrevistado pense melhor em suas respostas, faça relatos mais detalhados e envie qualquer documentação de suporte que quiser.

### Referências que usei
- [Avoid Leading Questions to Get Better Insights from Participants](https://www.nngroup.com/articles/leading-questions/)
- [5 Steps to Create Good User Interview Questions By @Metacole — A Comprehensive Guide](https://medium.com/interactive-mind/5-steps-to-create-good-user-interview-questions-by-metacole-a-comprehensive-guide-8a591b0e2162)
