### ISSUE TITLE
Reunião 22/09/2020

### ISSUE THREAD

**Issue by BrunaNayara** [BOSS-BigOpenSourceSister/BigSister#68]
_Edite esse template antes da reunião com  as pautas a serem discutidas. Incentive sugestões de pauta nos comemtários. Formalize as decisões das reuniões aqui. Não se esqueça de fechar a issue após a reunião e a revisão da ata._

# Reunião semanal 

- **Data:** 22 de setembro de 2020
- **Ata da reunião anterior**: #58 

## Ata
_Adicione os itens a serem discutidos durante a reunião. Certifique-se de que você estará presente na reunião, pois a ata só pode ser editada por quem a criou_

### Acompanhamento das ações pendentes da última reunião

- [x] Criar votação no grupo sobre a data de checkpoint (@carolinaferreira) 
- [x] Adicionar o link da apresentação da aula no template da issue. Adicionar na descrição do youtube. (@BrunaNayara )
- [x] Refatorar a pasta do drive (@dehatanes )
- [x] Responder email da gnome (@RochaCarla )
- [x] Comunicação sobre entrevistas lá no grupo (@Joranhezon)
- [ ] Comunicar sobre os grupos de comunidade (@RochaCarla e mentoras nas 1:1)
- [ ] Definir processo e documentar de transcrição do conteúdo (@BrunaNayara ) Issue associada #67 
- [x] Ajustar nas redes sociais. Youtube / Twitter / Instagram / Readme github (@Joranhezon @naiieandrade )
- [ ] Guia de boas práticas da mentora #64 
- [ ] Guia de mentoria (1 mes apresentação/comunidade, 1 mês de mão na massa, 1 mês de contribuição)
- [X] Planejamento do Artigo (@BrunaNayara @RochaCarla @fabiolamfleury)

#### Operacional
- [ ]  Definir roadmap do 3º mês. 
- [ ]  Tópico 1: Essa é a ideia do tópico. **Essa foi a decisão final**

#### Checkpoint de mentoria
- [x]  Me parece que muitas mentoradas estão desanimadas, temos que ver o que fazer sobre.
- [x]  Discutir a viabilidade e possíveis atividades para encorajar engajamento da comunidade

### Tarefas criadas

- [ ] Refazer: Comunicar sobre os grupos de comunidade (@RochaCarla e mentoras nas 1:1) (Solução: Marcar um evento para fazermos pareamentos, de maneira a incentivar algumas mentoradas a quebrarem essa barreira.)
- [ ]  Definir processo e documentar de transcrição do conteúdo (@BrunaNayara ) Issue associada #67
- [ ]  Guia de boas práticas da mentora #64 (@naiieandrade )
- [ ] Roadmap (1 mes apresentação/comunidade, 1 mês de mão na massa, 1 mês de contribuição) ( @brunapinos )

@BOSS-BigOpenSourceSister/mentoras

**Comment by Joranhezon** [comment]
Essa também envolve o Checkpoint? Pode mandar assuntos pra falarmos do checkpoint aqui ou criamos outra issue?

**Comment by BrunaNayara** [comment]
Acho que como as duas reuniões ficaram no mesmso dia, acho que podemos deixar aqui. Se percebermos a necessidade, depois a gente pode quebrar. O que acham?

**Comment by dehatanes** [comment]
Talvez nem precisamos de ata pro Checkpoint, já que é algo que pode ser muito pessoal. Ou acham que faz sentido documentar?

**Comment by Joranhezon** [comment]
@BrunaNayara faz sentido deixar aqui sim. Mas acho que quando formos comentar melhor escrevermos no inicio **Operacional** ou **Checkpoint**, para sabermos em que  momento falar sobre o tópico.

@dehatanes Eu acho que faz muito sentido documentarmos. Também seria bom termos algumas perguntas genéricas pra fazermos ao inicio da reunião, pras pessoas irem pensando. Algo no sentido de: como está sua mentorada está reagindo nas ultimas semanas? Alguma dificuldade? etc.

Ai como vamos discutir pontos de melhoria e o que fazer relacionado a eles, se não documentarmos acho que vamos facilmente esquecer ou reter o conhecimento na pessoa que acabou aplicando uma ação específica.

**Comment by BrunaNayara** [comment]
Concordo com @Joranhezon. Acho que é importante documentarmos o que percebemos de problemas pra atacar e pontos de ação também.

**Comment by Joranhezon** [comment]
Então já indo no embalo:

**Checkpoint** - Me parece que muitas mentoradas estão desanimadas, temos que ver o que fazer sobre.

O que até me levou a pensar em outro ponto pro nosso Post Mortem que é se a data que escolhemos tá ideal considerando as participantes que teremos.(Mas isso a gente discute depois kkk)

**Comment by Joranhezon** [comment]
_Também tá mudada a BOSS no twitter pro feminino, mas não marquei porque não sei como está as outras redes._

**Comment by Joranhezon** [comment]
**Checkpoint** - Discutir a viabilidade e possíveis atividades para encorajar engajamento da comunidade

Acho que temos que voltar a discutir isso daqui, mas dessa vez tirarmos algumas ações mais concretas. Tendo em vista que semana passada falamos sobre isso e achamos que ainda não está muito legal.

**Comment by Joranhezon** [comment]
Solução: Marcar um evento para fazermos pareamentos, de maneira a incentivar algumas mentoradas a quebrarem essa barreira.

**Comment by BrunaNayara** [comment]
@Joranhezon você atualizou essa issue com a ata? Se não, atualiza e fecha? Se sim, só fecha :D Valeuuu
